name: Deploy MkDocs to gh-pages
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message,'[document]') &&
      github.repository == 'PlumyGames/mgpp'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force