name: Generate JavaDoc
on: workflow_dispatch

jobs:
  publish-and-doc:
    runs-on: ubuntu-latest
    if: github.repository == 'PlumyGames/mgpp'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build dokka doc
        run: |
          chmod +x gradlew
          ./gradlew :main:dokkaHtml

      - name: Update document
        run: |
          cd ../
          git clone --depth 1 https://github.com/PlumyGames/mgppDoc.git
          cp -r ./mgpp/main/build/dokka/html/* ./mgppDoc
          cd mgppDoc
          git add .
          git config --global user.email "Li_plum@outlook.com"
          git config --global user.name "liplum"
          git commit --allow-empty -m "${{ github.event.head_commit.message }}"
          git push https://Liplum:${{ secrets.API_TOKEN_GITHUB }}@github.com/PlumyGames/mgppDoc

