name: Push Test Building
on: [ push, pull_request ]

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Test mgpp
        run: |
          chmod +x gradlew
          ./gradlew :main:test

      - name: Build mgpp
        run: |
          chmod +x gradlew
          ./gradlew :main:publishToMavenLocal --info

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Test Kotlin DSL
        run: |
          cd TestProjectKt
          chmod +x gradlew
          ./gradlew :deployMod --info
          ./gradlew :antiAlias --info
          cd ..

      - name: Test Groovy DSL
        run: |
          cd TestProjectGroovy
          chmod +x gradlew
          ./gradlew :deployMod --info
          ./gradlew :antiAlias --info
          cd ..

      - name: Test Multi-Project
        run: |
          cd TestMultiproject
          chmod +x gradlew
          ./gradlew :main:deployMod --info
          ./gradlew :core:deployMod --info
          ./gradlew :js:zipMod --info
          cd ..

      - uses: actions/upload-artifact@v3
        with:
          name: mgpp-snapshot-build
          path: |
            main/build/libs/*.jar
            TestProjectKt/build/deployMod/*.jar
            TestProjectGroovy/build/deployMod/*.jar
            TestMultiproject/main/build/deployMod/*.jar
            TestMultiproject/core/build/deployMod/*.jar
            TestMultiproject/js/build/libs/*.zip
